/* PRO MUSIC — DATA PARTNERŮ (zdroj: promusic.cz/partneri, stav 16. 9. 2026)
   { n, name, img, web, brands[], cert[], cat: "rental" | "venue" }
   Pořadí n odpovídá pořadí na stávajícím webu. Loga jsou rastry max. 220 px —
   pro produkci vyžádat od partnerů vektorová loga (SVG). */
window.PM_PARTNERS = [
{n:1,cat:"rental",name:"High Lite Touring, s.r.o.",img:"assets/partneri/01-high-lite-touring-s-r-o.png",web:"www.highlite.cz",brands:["L-Acoustics","DiGiCo","ChamSys","Vari-Lite","Rational Acoustics","Waves"],cert:["K1","K2","KARA"]},
{n:2,cat:"rental",name:"T-Servis",img:"assets/partneri/02-t-servis.jpg",web:"",brands:["L-Acoustics","Yamaha","Luminex"],cert:["K1","KARA","KUDO"]},
{n:3,cat:"rental",name:"Pink Panther Agency",img:"assets/partneri/03-pink-panther-agency.gif",web:"www.pink-panther.cz",brands:["L-Acoustics","DiGiCo","Audio-Technica","Cybermotion","TEQSAS","Waves"],cert:[]},
{n:4,cat:"rental",name:"Laser Live",img:"assets/partneri/04-laser-live.jpg",web:"www.laserlive.sk",brands:["L-Acoustics"],cert:["K1","KARA","KUDO"]},
{n:5,cat:"rental",name:"Ministry",img:"assets/partneri/05-ministry.gif",web:"www.ministryrental.sk",brands:["L-Acoustics","Yamaha"],cert:["K2","KARA","KUDO"]},
{n:6,cat:"rental",name:"EVENTSUPPORT s.r.o.",img:"assets/partneri/06-eventsupport-s-r-o.png",web:"www.eventsupport.cz",brands:["L-Acoustics","DiGiCo","ChamSys","Luminex","Waves"],cert:[]},
{n:7,cat:"rental",name:"JESA Sound & Light Equipment",img:"assets/partneri/07-jesa-sound-light-equipment.png",web:"www.jesa.cz",brands:["L-Acoustics","DiGiCo","Yamaha"],cert:["K2","KARA","KUDO"]},
{n:8,cat:"rental",name:"Koncertservis",img:"assets/partneri/08-koncertservis.jpg",web:"",brands:["L-Acoustics","DiGiCo","ChamSys"],cert:[]},
{n:9,cat:"rental",name:"Start Production",img:"assets/partneri/09-start-production.png",web:"www.startproduction.cz",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:10,cat:"rental",name:"Borovka Rental",img:"assets/partneri/10-borovka-rental.png",web:"",brands:["L-Acoustics","DiGiCo","ChamSys","Waves"],cert:[]},
{n:11,cat:"rental",name:"Audioblue",img:"assets/partneri/11-audioblue.jpg",web:"www.audioblue.cz",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:12,cat:"rental",name:"ZL Production",img:"assets/partneri/12-zl-production.png",web:"www.zlproduction.cz",brands:["DiGiCo","ChamSys","Yamaha"],cert:[]},
{n:13,cat:"rental",name:"AVT Group",img:"assets/partneri/13-avt-group.png",web:"",brands:["L-Acoustics","DiGiCo","Yamaha"],cert:[]},
{n:14,cat:"rental",name:"Pragosound s.r.o.",img:"assets/partneri/14-pragosound-s-r-o.png",web:"www.pragosound.cz",brands:["DiGiCo"],cert:[]},
{n:15,cat:"rental",name:"Agentura Zvuk",img:"assets/partneri/15-agentura-zvuk.jpg",web:"",brands:["L-Acoustics"],cert:[]},
{n:16,cat:"rental",name:"Amex Audio",img:"assets/partneri/16-amex-audio.png",web:"www.amexaudio.sk",brands:["DiGiCo"],cert:[]},
{n:17,cat:"rental",name:"BMM Art",img:"assets/partneri/17-bmm-art.jpg",web:"",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:18,cat:"venue",name:"Česká Televize",img:"assets/partneri/18-ceska-televize.png",web:"",brands:["L-Acoustics"],cert:[]},
{n:19,cat:"venue",name:"Český Rozhlas",img:"assets/partneri/19-cesky-rozhlas.png",web:"",brands:["DiGiCo"],cert:[]},
{n:20,cat:"venue",name:"Club Epic Prague",img:"assets/partneri/20-club-epic-prague.jpg",web:"",brands:["L-Acoustics"],cert:[]},
{n:21,cat:"venue",name:"Colours of Ostrava",img:"assets/partneri/21-colours-of-ostrava.png",web:"",brands:["L-Acoustics"],cert:[]},
{n:22,cat:"rental",name:"Cross Audio",img:"assets/partneri/22-cross-audio.jpg",web:"www.crossaudio.cz",brands:["L-Acoustics","Yamaha"],cert:[]},
{n:23,cat:"rental",name:"Danceshow",img:"assets/partneri/23-danceshow.jpg",web:"www.danceshow.cz",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:24,cat:"venue",name:"Divadlo Hybernia",img:"assets/partneri/24-divadlo-hybernia.png",web:"",brands:["DiGiCo"],cert:[]},
{n:25,cat:"venue",name:"Divadlo Josefa Kajetána Tyla Plzeň",img:"assets/partneri/25-divadlo-josefa-kajetana-tyla-plzen.png",web:"",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:26,cat:"venue",name:"Divadlo Minor",img:"assets/partneri/26-divadlo-minor.jpg",web:"",brands:["DiGiCo"],cert:[]},
{n:27,cat:"venue",name:"Divadlo na Orlí",img:"assets/partneri/27-divadlo-na-orli.jpg",web:"",brands:[],cert:[]},
{n:28,cat:"venue",name:"Dolní oblast Vítkovice",img:"assets/partneri/28-dolni-oblast-vitkovice.png",web:"",brands:[],cert:[]},
{n:29,cat:"venue",name:"DOX",img:"assets/partneri/29-dox.jpg",web:"",brands:[],cert:[]},
{n:30,cat:"rental",name:"EDWARD Sound and Light agency",img:"assets/partneri/30-edward-sound-and-light-agency.gif",web:"www.edward.cz",brands:["L-Acoustics","Yamaha"],cert:[]},
{n:31,cat:"rental",name:"F.O.H s.r.o.",img:"assets/partneri/31-f-o-h-s-r-o.jpg",web:"www.fohsro.cz",brands:["L-Acoustics","Yamaha"],cert:[]},
{n:32,cat:"venue",name:"Forum Karlín",img:"assets/partneri/32-forum-karlin.jpg",web:"",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:33,cat:"rental",name:"Friends Media Slovakia s.r.o.",img:"assets/partneri/33-friends-media-slovakia-s-r-o.png",web:"www.friendsmedia.sk",brands:["L-Acoustics"],cert:[]},
{n:34,cat:"venue",name:"Kongresové Centrum Praha",img:"assets/partneri/34-kongresove-centrum-praha.png",web:"",brands:["DiGiCo","ChamSys"],cert:[]},
{n:35,cat:"venue",name:"Lucerna Music Bar",img:"assets/partneri/35-lucerna-music-bar.jpg",web:"",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:36,cat:"rental",name:"Milan Andrle Sound Systems",img:"assets/partneri/36-milan-andrle-sound-systems.png",web:"www.andrlemilan.cz",brands:["DiGiCo","ChamSys"],cert:[]},
{n:37,cat:"venue",name:"Národní Divadlo",img:"assets/partneri/37-narodni-divadlo.png",web:"",brands:["DiGiCo"],cert:[]},
{n:38,cat:"venue",name:"Národní Divadlo Brno",img:"assets/partneri/38-narodni-divadlo-brno.jpg",web:"",brands:[],cert:[]},
{n:39,cat:"rental",name:"Petr Frýdecký",img:"assets/partneri/39-petr-frydecky.png",web:"www.prime-sound.cz",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:40,cat:"rental",name:"Produkce na jedničku",img:"assets/partneri/40-produkce-na-jednicku.png",web:"www.produkce1.cz",brands:["L-Acoustics"],cert:[]},
{n:41,cat:"rental",name:"Q-99",img:"assets/partneri/41-q-99.jpg",web:"www.q-99.sk",brands:["L-Acoustics"],cert:[]},
{n:42,cat:"rental",name:"Quix Event",img:"assets/partneri/42-quix-event.png",web:"www.quix.cz",brands:["DiGiCo"],cert:[]},
{n:43,cat:"rental",name:"Remak Agency",img:"assets/partneri/43-remak-agency.png",web:"www.remakagency.cz",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:44,cat:"rental",name:"Rock Audio",img:"assets/partneri/44-rock-audio.jpg",web:"www.rockaudio.cz",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:45,cat:"venue",name:"Roxy Club Prague",img:"assets/partneri/45-roxy-club-prague.jpg",web:"",brands:["L-Acoustics"],cert:[]},
{n:46,cat:"rental",name:"Silent Sound",img:"assets/partneri/46-silent-sound.png",web:"www.silentsound.cz",brands:["L-Acoustics","Yamaha"],cert:[]},
{n:47,cat:"venue",name:"ŠKODA AUTO Muzeum",img:"assets/partneri/47-skoda-auto-muzeum.png",web:"",brands:["L-Acoustics","DiGiCo","Vari-Lite","Ayrton","Waves"],cert:[]},
{n:48,cat:"rental",name:"SMART Production",img:"assets/partneri/48-smart-production.png",web:"www.smartproduction.cz",brands:["L-Acoustics"],cert:[]},
{n:49,cat:"rental",name:"SONING Praha a.s.",img:"assets/partneri/49-soning-praha-a-s.png",web:"www.soning.cz",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:50,cat:"venue",name:"SONO centrum",img:"assets/partneri/50-sono-centrum.jpg",web:"",brands:["L-Acoustics"],cert:[]},
{n:51,cat:"venue",name:"UFFO",img:"assets/partneri/51-uffo.jpg",web:"",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:52,cat:"rental",name:"AV media",img:"assets/partneri/52-av-media.png",web:"www.avmedia.cz",brands:["L-Acoustics"],cert:[]},
{n:53,cat:"rental",name:"Balonton",img:"assets/partneri/53-balonton.jpg",web:"",brands:["DiGiCo"],cert:[]},
{n:54,cat:"rental",name:"Bohemia Sound",img:"assets/partneri/54-bohemia-sound.jpg",web:"www.bohemia-sound.cz",brands:["DiGiCo"],cert:[]},
{n:55,cat:"rental",name:"Csound",img:"assets/partneri/55-csound.jpg",web:"",brands:["L-Acoustics","DiGiCo"],cert:[]},
{n:56,cat:"rental",name:"Eventlive",img:"assets/partneri/56-eventlive.jpg",web:"",brands:["DiGiCo","ChamSys"],cert:[]},
{n:57,cat:"rental",name:"Libor Chadraba",img:"assets/partneri/57-libor-chadraba.jpg",web:"www.zvuk-drak.cz",brands:["DiGiCo"],cert:[]},
{n:58,cat:"rental",name:"MASOUND",img:"assets/partneri/58-masound.jpg",web:"",brands:["L-Acoustics"],cert:[]},
{n:59,cat:"rental",name:"Professional Sound",img:"assets/partneri/59-professional-sound.png",web:"",brands:["DiGiCo"],cert:[]},
{n:60,cat:"rental",name:"S-System",img:"assets/partneri/60-s-system.jpg",web:"www.s-system.cz",brands:["DiGiCo"],cert:[]},
{n:61,cat:"rental",name:"Solitec rental",img:"assets/partneri/61-solitec-rental.jpg",web:"",brands:["ChamSys"],cert:[]},
{n:62,cat:"rental",name:"Švejk Team",img:"assets/partneri/62-svejk-team.jpg",web:"www.svejkteam.cz",brands:["ChamSys"],cert:[]}
];
