/* PRO MUSIC — DATA PROJEKTŮ
   Jediný zdroj pravdy pro výpisy Live & turné a Stálé instalace.
   Zdroj obsahu: promusic.cz/stitky/reference.

   ⚠️ PRAVIDLO OBSAHU: všechna pole jsou PARAMETRY, ne věty.
   Hodnota se nesklonuje a nekomentuje — „DiGiCo SD5", nikdy „poprvé s DiGiCo SD5".
   Prózu (příběh projektu) nese až stránka detailu, ne karta ve výpisu.
   Seznam parametrů pro import z Pohody E1: viz parametry-pohoda.md

   LIVE: [Název, Kategorie, Rok, Místo, Technika(|), Rozsah(|), ZeSvěta 0/1]
   INST: [Název, Kategorie, Město, Rok, Technika(|), Kapacita]
   Prázdná hodnota = parametr nevyplněn → do UI se nevykreslí. */
(function () {
  "use strict";
  var P = "assets/projekty/";

  /* Fotka a case study se párují podle Názvu — ne podle kategorie. */
  var PHOTO = {
    "Ed Sheeran — Mathematics Tour": P + "ed-sheeran/ohnostroj.jpg",
    "Steel Aréna Košice": P + "steel-arena/projekce-barvy.jpg",
    "Hudební divadlo Karlín": P + "karlin/zvukar-foh.jpg",
    "Nová scéna DJKT Plzeň": P + "djkt-plzen/array-strop.jpg"
  };
  var CASE = {
    "Ed Sheeran — Mathematics Tour": "live-ed-sheeran.html",
    "Hudební divadlo Karlín": "instalace-hd-karlin-schema.html"
  };

  /* Poznámka = podklad pro detail projektu. Na kartu se NEVYKRESLUJE. */
  var NOTE = {
    "Hudební divadlo Karlín": "Největší instalace L-ISA v ČR. Konzole DiGiCo Quantum 7T.",
    "Nová scéna DJKT Plzeň": "Světová premiéra systému virtuální akustiky Ambiance.",
    "Steel Aréna Košice": "Osvětlení multifunkční hokejové arény.",
    "Společenské centrum UFFO": "První L-ISA v České republice.",
    "Nové divadlo Plzeň": "Nejmodernější kulturní stánek ve střední Evropě.",
    "Divadlo Husa na provázku": "První instalace interkomu ASL FLEXUS v ČR.",
    "Přenosový vůz Českého rozhlasu": "Srdce nového přenosového vozu.",
    "Česká televize": "Postupné rozšiřování systému.",
    "Velký sál Městské knihovny": "Sál zní mnohem lépe.",
    "Státní opera": "Pulty řady SD v kulturní klenotnici.",
    "Divadlo Petra Bezruče": "Rekonstrukce sálu.",
    "Filharmonie Hradec Králové": "FHK v novém.",
    "Lucerna Music Bar": "Posílený světelný rig.",
    "ROXY": "Srdce sound systému klubu.",
    "Gong": "Místo plynu zvuk.",
    "Zimní stadion Trutnov": "Zahájení sezóny s novým ozvučením.",
    "Středisko volného času": "Multifunkční prostor s AV technologií.",
    "Up Group — restaurace": "K dobrému jídlu patří příjemná hudba."
  };

  window.PM_LIVE_CATS = ["Turné", "Festivaly", "Koncerty", "TV & broadcast", "Eventy & korporát"];
  var LIVE = [
    ["Ed Sheeran — Mathematics Tour", "Turné", "2022", "", "Ayrton", "", 1],
    ["Rammstein", "Turné", "2019", "", "L-Acoustics", "34 koncertů|17 zemí", 1],
    ["Eurovision Song Contest", "TV & broadcast", "2024", "", "Ayrton", "", 1],
    ["Colours of Ostrava", "Festivaly", "", "", "DiGiCo", "", 0],
    ["Let it Roll", "Festivaly", "", "", "L-Acoustics|DiGiCo", "", 0],
    ["Kabát — turné", "Turné", "2017", "", "L-Acoustics", "", 0],
    ["CityFest Pardubice", "Festivaly", "2016", "", "L-Acoustics K2|ChamSys MagicQ MQ300", "", 0],
    ["Habera & Team 33 Tour", "Turné", "", "", "L-Acoustics|ChamSys", "", 0],
    ["Kabát Open Air", "Festivaly", "2015", "", "L-Acoustics", "", 0],
    ["Kabát na Vypichu", "Koncerty", "", "", "L-Acoustics", "", 0],
    ["LUCIE — turné", "Turné", "2014", "", "L-Acoustics|DiGiCo|Vari*Lite|Earthworks|Audio-Technica", "", 0],
    ["Kabát — turné", "Turné", "2013", "", "DiGiCo SD5|L-Acoustics K1", "", 0],
    ["Snow Jam", "Festivaly", "2013", "", "", "", 0],
    ["Kryštof", "Turné", "", "", "L-Acoustics|Vari*Lite", "", 0],
    ["50 let Olympic", "Turné", "", "", "L-Acoustics|DiGiCo", "", 0],
    ["Karel Gott — Pardubice", "Koncerty", "", "", "L-Acoustics|DiGiCo|Audio-Technica", "", 0],
    ["Wanastowky na Wenuši", "Koncerty", "", "", "L-Acoustics|DiGiCo|Earthworks|Audio-Technica", "", 0],
    ["Red Hot Chili Peppers", "Turné", "", "", "L-Acoustics K1", "", 0],
    ["Michal Pavlíček — Na Kloboučku", "Koncerty", "", "", "L-Acoustics|DiGiCo SD Ten", "", 0],
    ["Oslava narozenin Václava Havla", "Eventy & korporát", "", "", "L-Acoustics|DiGiCo", "", 0],
    ["Daniel Landa — turné", "Turné", "2011", "", "L-Acoustics|Vari*Lite", "", 0],
    ["StreetFest Malacky", "Festivaly", "2011", "SK", "", "", 0],
    ["Plácido Domingo", "Koncerty", "", "Český Krumlov", "L-Acoustics", "", 0],
    ["Open Air Music Festival Trutnov", "Festivaly", "2011", "", "L-Acoustics K1", "", 0],
    ["Sázava Fest", "Festivaly", "2011", "", "L-Acoustics", "", 0],
    ["Street Dance Kemp", "Festivaly", "2011", "", "L-Acoustics KARA", "", 0],
    ["Pohoda", "Festivaly", "2011", "Trenčín, SK", "", "", 0],
    ["Colours of Ostrava", "Festivaly", "2011", "", "", "", 0],
    ["Masters of Rock", "Festivaly", "2011", "", "", "", 0],
    ["Topfest", "Festivaly", "2011", "", "L-Acoustics", "", 0],
    ["Wake Jam", "Festivaly", "2011", "", "L-Acoustics|DiGiCo", "", 0],
    ["Prague City Festival", "Festivaly", "2011", "", "", "", 0],
    ["Sonisphere", "Festivaly", "2011", "", "", "", 0],
    ["Pražské jaro — Symfonie tisíců", "Koncerty", "2011", "", "L-Acoustics", "", 0],
    ["Elán", "Koncerty", "", "", "L-Acoustics K1", "", 0],
    ["Free Day in Q-99", "Festivaly", "", "", "", "", 0],
    ["Quiksilver Snowjam", "Festivaly", "2011", "", "", "", 0],
    ["Plácido Domingo — Bratislava", "Koncerty", "", "", "", "", 0],
    ["Pietro e Lucia", "Koncerty", "", "", "", "", 0],
    ["Hudební ceny Óčka", "TV & broadcast", "2010", "", "L-Acoustics|DiGiCo", "", 0],
    ["Lucie Bílá — Bílé Vánoce", "Koncerty", "", "", "", "", 0],
    ["AnnaK v Lucerně", "Koncerty", "", "", "", "", 0],
    ["Elán Tour", "Turné", "2010", "", "", "", 0],
    ["Chinaski t-music tour", "Turné", "2010", "", "", "", 0],
    ["Karel Gott a Eva Urbanová", "Turné", "2010", "", "", "", 0],
    ["Mrazík — muzikál na ledě", "Eventy & korporát", "", "", "", "", 0],
    ["Open Air Festival Panenský Týnec", "Festivaly", "2010", "", "", "", 0],
    ["Open Air Music Festival Trutnov", "Festivaly", "2010", "", "", "", 0],
    ["Benátská noc", "Festivaly", "2010", "Malá Skála", "", "", 0],
    ["Colours of Ostrava", "Festivaly", "2010", "", "", "", 0],
    ["Pleasure Island", "Festivaly", "2010", "", "", "", 0],
    ["Rock for People", "Festivaly", "2010", "", "", "", 0],
    ["Sázavafest", "Festivaly", "2010", "", "", "", 0],
    ["Topfest", "Festivaly", "2010", "", "", "", 0],
    ["Sonisphere", "Festivaly", "2010", "", "", "", 0],
    ["Michal David — Mejdan roku", "Koncerty", "", "", "", "", 0],
    ["Quiksilver Wake Jam", "Festivaly", "2010", "", "", "", 0],
    ["Votvírák", "Festivaly", "2010", "", "", "", 0],
    ["Quiksilver Snowjam", "Festivaly", "2010", "", "", "", 0],
    ["Muzikál Ježíš", "Eventy & korporát", "", "", "", "", 0],
    ["Zvukařský kurz Jindry Varhana", "Eventy & korporát", "", "", "", "", 0],
    ["Děti ráje", "Eventy & korporát", "", "", "", "", 0],
    ["Kabát — Po čertech velkej koncert", "Koncerty", "", "", "", "", 0],
    ["Topfest Zelená Voda", "Festivaly", "2009", "SK", "", "", 0],
    ["Quiksilver Snow Jam", "Festivaly", "2009", "", "", "", 0],
    ["Žebřík", "TV & broadcast", "2009", "", "", "", 0],
    ["Hudební ceny TV Óčko", "TV & broadcast", "2009", "", "", "", 0],
    ["Fashion Club Bratislava", "Eventy & korporát", "", "", "", "", 0],
    ["Megakoncert Rádia Čas", "Koncerty", "", "", "", "", 0],
    ["Kontrafakt Tour", "Turné", "2008", "", "L-Acoustics KIVA", "", 0],
    ["Lucerna Music Bar", "Koncerty", "", "Praha", "DiGiCo SD7|DiGiCo D5", "", 0],
    ["O2 arena", "Koncerty", "", "Praha", "L-Acoustics KIVA", "", 0],
    ["Hip Hop Kemp", "Festivaly", "2008", "", "", "", 0],
    ["Sázavafest", "Festivaly", "2008", "", "L-Acoustics", "", 0],
    ["Subculture Fest", "Festivaly", "2008", "", "", "", 0],
    ["Colours of Ostrava", "Festivaly", "2008", "", "", "", 0],
    ["Suzanne Vega", "Koncerty", "", "", "", "", 0],
    ["Czech & Slovak Surfing Championship", "Eventy & korporát", "", "", "", "", 0],
    ["Masters of Rock", "Festivaly", "2008", "", "", "", 0],
    ["Topfest", "Festivaly", "2008", "", "", "", 0],
    ["Trutnovský zimák", "Koncerty", "2008", "", "", "", 0],
    ["TEAM — The Best of Tour", "Turné", "2008", "", "", "", 0],
    ["Hudební ceny TV Óčko", "TV & broadcast", "2008", "", "", "", 0],
    ["Otevření OC Palladium", "Eventy & korporát", "", "", "", "", 0],
    ["Hip Hop Kemp", "Festivaly", "2007", "", "", "", 0],
    ["Mácháč", "Festivaly", "2007", "", "", "", 0],
    ["Open Air Music Festival Trutnov", "Festivaly", "2007", "", "", "", 0],
    ["Summer of Love", "Festivaly", "", "", "", "", 0],
    ["O2 Sázavafest", "Festivaly", "2007", "", "", "", 0],
    ["t-music Hip Hop Jam", "Festivaly", "", "", "", "", 0],
    ["Masters of Rock", "Festivaly", "2007", "", "", "", 0],
    ["Colours of Ostrava", "Festivaly", "2007", "", "", "", 0],
    ["JESA na Colours of Ostrava", "Festivaly", "", "", "", "", 0],
    ["České Hrady", "Festivaly", "2007", "", "", "", 0],
    ["Mighty Sounds", "Festivaly", "", "", "", "", 0],
    ["Hodokvas Piešťany", "Festivaly", "2007", "SK", "", "", 0],
    ["Rock for People", "Festivaly", "", "", "L-Acoustics", "", 0],
    ["Apollo 440 v Roxy", "Koncerty", "", "", "", "", 0],
    ["Reggae Etnic Session", "Festivaly", "", "", "", "", 0],
    ["Sensation White", "Festivaly", "", "", "L-Acoustics KIVA", "30 000 lidí", 0],
    ["Monkey Business — Nokia Tour", "Turné", "", "", "", "", 0],
    ["Scorpions", "Koncerty", "", "", "", "", 0],
    ["Žebřík", "TV & broadcast", "2007", "", "", "", 0],
    ["Hudební ceny TV Óčko", "TV & broadcast", "2007", "", "", "", 0],
    ["Česká televize", "TV & broadcast", "", "", "L-Acoustics", "", 0],
    ["Rock for People", "Festivaly", "", "", "DiGiCo", "", 0],
    ["Český rozhlas", "TV & broadcast", "", "", "DiGiCo", "", 0],
    ["Coachella Valley", "Festivaly", "", "", "L-Acoustics|DiGiCo", "", 1],
    ["Coachella", "Festivaly", "2019", "", "DiGiCo", "", 1],
    ["Tomorrowland — Atmosphere Stage", "Festivaly", "", "", "L-Acoustics L-ISA", "", 1],
    ["Tomorrowland", "Festivaly", "", "", "L-Acoustics", "", 1],
    ["Grammy Awards", "TV & broadcast", "2019", "", "DiGiCo SD7", "", 1],
    ["Aerosmith — Las Vegas", "Koncerty", "", "", "DiGiCo|L-Acoustics L-ISA", "", 1],
    ["Iron Maiden", "Turné", "", "", "", "", 1],
    ["Star Wars in Concert", "Koncerty", "", "", "L-Acoustics L-ISA", "", 1],
    ["Alt-J", "Koncerty", "", "", "", "", 1],
    ["Ennio Morricone — Milán", "Koncerty", "", "", "L-Acoustics L-ISA", "", 1],
    ["Rammstein — Horsens", "Koncerty", "", "", "CyberHoist", "", 1],
    ["Arizona Cardinals", "Eventy & korporát", "", "", "L-Acoustics", "", 1],
    ["Disney v Berlíně", "Koncerty", "", "", "L-Acoustics L-ISA", "", 1],
    ["Světový den mládeže", "Eventy & korporát", "", "", "DiGiCo SD5", "", 1],
    ["Sting & Peter Gabriel", "Turné", "", "", "L-Acoustics", "", 1],
    ["Adele", "Turné", "", "", "L-Acoustics K2|DiGiCo SD7", "", 1],
    ["AC/DC — Rock or Bust", "Turné", "", "Wembley", "Vari*Lite VL4000 BeamWash", "", 1],
    ["Justin Timberlake — 20/20 Experience", "Turné", "", "", "L-Acoustics|DiGiCo|Vari*Lite|Audio-Technica", "", 1],
    ["Hollywood Bowl", "Koncerty", "", "", "L-Acoustics K1", "", 1],
    ["Robbie Williams — Take the Crown", "Turné", "", "", "L-Acoustics", "", 1],
    ["PINK — The Truth About Love", "Turné", "", "", "L-Acoustics", "", 1],
    ["Machu Picchu", "Eventy & korporát", "", "", "DiGiCo|Vari*Lite", "", 1],
    ["Black Box Music", "Turné", "", "", "L-Acoustics K1", "", 1],
    ["Kylie Minogue — Les Folies Tour", "Turné", "2011", "", "L-Acoustics K1", "", 1],
    ["Miss Universe SR", "Eventy & korporát", "2011", "", "L-Acoustics KARA", "", 1],
    ["Zlatý koncert", "Koncerty", "2010", "", "L-Acoustics KARA", "", 1],
    ["Red Hot Chili Peppers", "Turné", "", "", "L-Acoustics", "", 1],
    ["Live Earth", "Festivaly", "2007", "", "", "", 1],
    ["Linkin Park & Marilyn Manson", "Koncerty", "", "", "", "", 1],
    ["Apocalyptica", "Turné", "", "", "L-Acoustics|DiGiCo", "", 1],
    ["Tuacahn Center for the Arts", "Koncerty", "", "", "L-Acoustics", "", 1],
  ];

  window.PM_INST_CATS = ["Divadla & sály", "Arény & stadiony", "Kluby & venues",
    "Broadcast & studia", "Školy & konzervatoře", "Hotely & gastro", "Veřejné prostory"];
  var INST = [
    ["Hudební divadlo Karlín", "Divadla & sály", "Praha", "", "L-Acoustics L-ISA|DiGiCo Quantum 7T", ""],
    ["Nová scéna DJKT Plzeň", "Divadla & sály", "Plzeň", "", "L-Acoustics Ambiance", ""],
    ["Steel Aréna Košice", "Arény & stadiony", "Košice, SK", "", "Ayrton Domino Profile", ""],
    ["Společenské centrum UFFO", "Divadla & sály", "Trutnov", "", "L-Acoustics L-ISA", ""],
    ["Nové divadlo Plzeň", "Divadla & sály", "Plzeň", "", "L-Acoustics|DiGiCo", ""],
    ["Divadlo Husa na provázku", "Divadla & sály", "Brno", "", "ASL FLEXUS", ""],
    ["Přenosový vůz Českého rozhlasu", "Broadcast & studia", "Praha", "", "DiGiCo Quantum 338", ""],
    ["Český rozhlas — přenosy", "Broadcast & studia", "Praha", "", "DiGiCo SD12", ""],
    ["Česká televize", "Broadcast & studia", "Praha", "", "L-Acoustics", ""],
    ["Velký sál Městské knihovny", "Divadla & sály", "Praha", "", "", ""],
    ["Státní opera", "Divadla & sály", "Praha", "", "DiGiCo", ""],
    ["Stavovské divadlo", "Divadla & sály", "Praha", "", "DiGiCo SD10|DiGiCo SD11", ""],
    ["Divadlo Minor", "Divadla & sály", "Praha", "", "DiGiCo", ""],
    ["Divadlo Hybernia", "Divadla & sály", "Praha", "", "", ""],
    ["Divadlo Kalich", "Divadla & sály", "Praha", "", "", ""],
    ["Divadlo Alfa", "Divadla & sály", "Plzeň", "", "", ""],
    ["Divadlo Petra Bezruče", "Divadla & sály", "Ostrava", "", "L-Acoustics", ""],
    ["Divadlo Stará Střelnice", "Divadla & sály", "Hranice na Moravě", "", "", ""],
    ["Městské divadlo Kolín", "Divadla & sály", "Kolín", "", "ASL Intercom", ""],
    ["Filharmonie Hradec Králové", "Divadla & sály", "Hradec Králové", "", "L-Acoustics", ""],
    ["PaS de Theatre & Shakespeare", "Divadla & sály", "", "", "L-Acoustics|DiGiCo", ""],
    ["Lucerna Music Bar", "Kluby & venues", "Praha", "", "ChamSys MagicQ MQ100", ""],
    ["ROXY", "Kluby & venues", "Praha", "", "L-Acoustics KARA", ""],
    ["Malostranská Beseda", "Kluby & venues", "Praha", "", "L-Acoustics|DiGiCo", ""],
    ["RETRO Music Hall", "Kluby & venues", "Praha", "", "", ""],
    ["Meinl Dance", "Kluby & venues", "Nový Jičín", "", "L-Acoustics", ""],
    ["DAYLONG cafe · disco · club", "Kluby & venues", "", "", "", ""],
    ["Gong", "Veřejné prostory", "Ostrava", "", "L-Acoustics", ""],
    ["Galerie města Kolína", "Veřejné prostory", "Kolín", "", "BELL", ""],
    ["Hala Královka", "Arény & stadiony", "Praha", "", "L-Acoustics ARCS Wide", ""],
    ["Zimní stadion Trutnov", "Arény & stadiony", "Trutnov", "", "BELL", ""],
    ["JAMU — HDL", "Školy & konzervatoře", "Brno", "", "DiGiCo SD9", ""],
    ["Pražská konzervatoř", "Školy & konzervatoře", "Praha", "", "", ""],
    ["Kalimeta — centrum vzdělávání a relaxace", "Školy & konzervatoře", "", "", "L-Acoustics", ""],
    ["Středisko volného času", "Školy & konzervatoře", "", "", "", ""],
    ["Up Group — restaurace", "Hotely & gastro", "", "", "Yamaha", ""],
    ["Grund hotel", "Hotely & gastro", "Mladé Buky", "", "", ""],
    ["ŠKODA — prezentace nových vozů", "Veřejné prostory", "", "", "Vari*Lite", ""],
  ];

  function split(s) { return (s || "").split("|").filter(Boolean); }
  window.PM_LIVE = LIVE.map(function (r) {
    return { t: r[0], cat: r[1], year: r[2], place: r[3], tech: split(r[4]), scale: split(r[5]),
      world: !!r[6], note: NOTE[r[0]] || "", img: PHOTO[r[0]] || "", href: CASE[r[0]] || "" };
  });
  window.PM_INST = INST.map(function (r) {
    return { t: r[0], cat: r[1], city: r[2], year: r[3], tech: split(r[4]), cap: r[5],
      note: NOTE[r[0]] || "", img: PHOTO[r[0]] || "", href: CASE[r[0]] || "" };
  });
})();
